In [1]:
import pandas as pd

In [2]:
datapath = 'data/'

**Question 1:**

In [3]:
orders = pd.read_csv(datapath + 'orders.csv')
orders

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign
...,...,...,...,...,...,...,...,...
646940,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign
646941,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral
646942,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign
646943,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct
646944,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  int64
 1   order_date      646945 non-null  str
 2   customer_id     646945 non-null  int64
 3   zip             646945 non-null  int64
 4   order_status    646945 non-null  str
 5   payment_method  646945 non-null  str
 6   device_type     646945 non-null  str
 7   order_source    646945 non-null  str
dtypes: int64(3), str(5)
memory usage: 39.5 MB

In [5]:
orders.head()

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign

In [6]:
orders = orders.sort_values(['customer_id', 'order_date'])
orders

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search
...,...,...,...,...,...,...,...,...
549990,709267,2020-04-11,157563,59937,delivered,credit_card,mobile,email_campaign
557438,718824,2020-05-29,157563,59937,delivered,credit_card,mobile,social_media
559725,721751,2020-06-22,157563,59937,delivered,paypal,tablet,organic_search
591841,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media
637881,822601,2022-08-31,157563,59937,cancelled,cod,desktop,social_media

In [7]:
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['prev_date'] = orders.groupby('customer_id')['order_date'].shift(1)
orders

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,prev_date
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search,NaT
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral,2012-07-25
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search,2014-05-31
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search,2015-07-31
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search,2017-04-23
...,...,...,...,...,...,...,...,...,...
549990,709267,2020-04-11,157563,59937,delivered,credit_card,mobile,email_campaign,2019-08-30
557438,718824,2020-05-29,157563,59937,delivered,credit_card,mobile,social_media,2020-04-11
559725,721751,2020-06-22,157563,59937,delivered,paypal,tablet,organic_search,2020-05-29
591841,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media,2020-06-22
637881,822601,2022-08-31,157563,59937,cancelled,cod,desktop,social_media,2021-05-27

In [8]:
orders['order_gap'] = orders['order_date'] - orders['prev_date']
orders.head()

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,prev_date,order_gap
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search,NaT,NaT
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral,2012-07-25,675 days
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search,2014-05-31,426 days
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search,2015-07-31,632 days
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search,2017-04-23,1037 days

In [9]:
gaps = orders.dropna(subset=['order_gap'])['order_gap']
median_gap = gaps.median()
median_gap

Timedelta('144 days 00:00:00')

**Answer:** C. 144 ngày

**Question 2:**

In [10]:
products = pd.read_csv(datapath + 'products.csv')
products

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406
...,...,...,...,...,...,...,...,...
2407,1260,VietMode MP-28,Casual,Activewear,S,red,4603.340000,2553.933032
2408,1261,VietMode MP-29,Casual,Activewear,M,black,5983.876433,4653.660702
2409,1262,VietMode MP-30,Casual,Activewear,L,orange,5983.876433,5684.682611
2410,1263,VietMode MP-31,Casual,Activewear,XL,blue,5984.370000,5685.151500
2411,1264,VietMode MP-32,Casual,Activewear,S,white,5984.370000,3719.884392

In [11]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2412 non-null   int64
 1   product_name  2412 non-null   str
 2   category      2412 non-null   str
 3   segment       2412 non-null   str
 4   size          2412 non-null   str
 5   color         2412 non-null   str
 6   price         2412 non-null   float64
 7   cogs          2412 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 150.9 KB

In [12]:
products.head()

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

In [13]:
products['ratio'] = (products['price'] - products['cogs']) / products['price']
products.groupby(['segment'])['ratio'].mean().sort_values(ascending=False)

segment
Standard       0.313442
Premium        0.285377
All-weather    0.284176
Activewear     0.265600
Performance    0.263650
Balanced       0.258038
Trendy         0.240758
Everyday       0.236343
Name: ratio, dtype: float64

**Answer:** D. Standard

**Question 3:**

In [14]:
returns = pd.read_csv(datapath + 'returns.csv')
returns

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76
...,...,...,...,...,...,...,...
39934,RET-051470,832867,653,2022-12-27,wrong_size,3,24741.62
39935,RET-051471,832890,792,2022-12-30,late_delivery,1,560.50
39936,RET-051481,833005,449,2022-12-31,defective,1,10002.55
39937,RET-051494,833234,1085,2022-12-28,wrong_size,1,815.57
39938,RET-051504,833351,2254,2022-12-30,late_delivery,3,1643.47

In [15]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 39939 entries, 0 to 39938
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   return_id        39939 non-null  str
 1   order_id         39939 non-null  int64
 2   product_id       39939 non-null  int64
 3   return_date      39939 non-null  str
 4   return_reason    39939 non-null  str
 5   return_quantity  39939 non-null  int64
 6   refund_amount    39939 non-null  float64
dtypes: float64(1), int64(3), str(3)
memory usage: 2.1 MB

In [16]:
returns.head()

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76

In [17]:
streetwear_returns = returns.merge(products[['product_id', 'category']], on='product_id')

In [18]:
streetwear_returns = streetwear_returns[streetwear_returns['category'] == 'Streetwear']

In [19]:
streetwear_returns['return_reason'].value_counts()

return_reason
wrong_size          7626
defective           4330
not_as_described    3854
changed_mind        3830
late_delivery       2159
Name: count, dtype: int64

**Answer:** B. wrong_size

**Question 4:**

In [20]:
web_traffic = pd.read_csv(datapath + 'web_traffic.csv')
web_traffic

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral
...,...,...,...,...,...,...,...
3647,2022-12-27,17416,13150,62527,0.00506,252.4,organic_search
3648,2022-12-28,21071,15979,67456,0.00560,177.3,organic_search
3649,2022-12-29,20884,14640,82155,0.00522,165.6,direct
3650,2022-12-30,17679,13713,79308,0.00350,183.8,email_campaign
3651,2022-12-31,21743,15512,94844,0.00394,151.7,organic_search

In [21]:
web_traffic.info()

<class 'pandas.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      3652 non-null   str
 1   sessions                  3652 non-null   int64
 2   unique_visitors           3652 non-null   int64
 3   page_views                3652 non-null   int64
 4   bounce_rate               3652 non-null   float64
 5   avg_session_duration_sec  3652 non-null   float64
 6   traffic_source            3652 non-null   str
dtypes: float64(2), int64(3), str(2)
memory usage: 199.8 KB

In [22]:
web_traffic.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

In [23]:
web_traffic.groupby('traffic_source')['bounce_rate'].mean().sort_values(ascending=True)

traffic_source
email_campaign    0.004458
social_media      0.004476
paid_search       0.004478
referral          0.004499
organic_search    0.004504
direct            0.004511
Name: bounce_rate, dtype: float64

**Answer:** C. email_campaign

**Question 5:**

In [24]:
order_items = pd.read_csv(datapath + 'order_items.csv')
order_items

/var/folders/wm/sz3_6dqj0cg6g4f6vrhdvccm0000gn/T/ipykernel_14069/4016070909.py:1: DtypeWarning: Columns (0: promo_id_2) have mixed types. Specify dtype option on import or set low_memory=False.
  order_items = pd.read_csv(datapath + 'order_items.csv')

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2
0,1,2400,7,1138.22,0.0,NaN,NaN
1,2,609,7,10166.25,0.0,NaN,NaN
2,3,396,3,11220.33,0.0,NaN,NaN
3,4,635,5,10639.25,0.0,NaN,NaN
4,6,1935,1,1597.84,0.0,NaN,NaN
...,...,...,...,...,...,...,...
714664,834372,690,8,4473.92,0.0,NaN,NaN
714665,834377,1995,7,5250.79,0.0,NaN,NaN
714666,834387,2331,8,7389.06,0.0,NaN,NaN
714667,834392,1115,5,4767.33,0.0,NaN,NaN
714668,834397,1118,1,4716.75,0.0,NaN,NaN

In [25]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 714669 entries, 0 to 714668
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         714669 non-null  int64
 1   product_id       714669 non-null  int64
 2   quantity         714669 non-null  int64
 3   unit_price       714669 non-null  float64
 4   discount_amount  714669 non-null  float64
 5   promo_id         276316 non-null  str
 6   promo_id_2       206 non-null     str
dtypes: float64(2), int64(3), str(2)
memory usage: 38.2 MB

In [26]:
order_items['promo_id'].count() / len(order_items)

np.float64(0.3866349316956521)

**Answer:** C. 39%

**Question 6:**

In [27]:
customers = pd.read_csv(datapath + 'customers.csv')
customers

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search
...,...,...,...,...,...,...,...
121925,157556,59936,Vung Tau,2016-03-03,Female,18-24,direct
121926,157557,59936,Vung Tau,2021-05-11,Female,45-54,social_media
121927,157558,59936,Vung Tau,2017-02-27,Female,25-34,referral
121928,157561,59937,Buon Ma Thuot,2018-10-15,Non-binary,45-54,paid_search
121929,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media

In [28]:
customers = customers[customers['age_group'].notna()]

In [29]:
customers_with_orders = customers.merge(orders, on='customer_id')
total_orders = customers_with_orders.groupby('age_group')['order_id'].count()
total_orders

age_group
18-24     89057
25-34    190622
35-44    170368
45-54    124138
55+       72760
Name: order_id, dtype: int64

In [30]:
num_customers = customers_with_orders.groupby('age_group')['customer_id'].nunique()
num_customers

age_group
18-24    12599
25-34    26802
35-44    23642
45-54    17193
55+      10010
Name: customer_id, dtype: int64

In [31]:
average_orders = total_orders / num_customers
average_orders.sort_values(ascending=False)

age_group
55+      7.268731
45-54    7.220264
35-44    7.206159
25-34    7.112230
18-24    7.068577
dtype: float64

**Answer:** A. 55+

**Question 7:**

In [32]:
geography = pd.read_csv(datapath + 'geography.csv')
geography

         zip           city region      district
0      15201      Hai Phong   East  District #13
1      15202         Phu Ly   East  District #13
2      15203       Viet Tri   East  District #13
3      15204      Bac Giang   East  District #13
4      15205      Bac Giang   East  District #13
...      ...            ...    ...           ...
39943  59933         Pleiku   West  District #33
39944  59934      Soc Trang   West  District #33
39945  59935       Rach Gia   West  District #33
39946  59936       Vung Tau   West  District #33
39947  59937  Buon Ma Thuot   West  District #33

[39948 rows x 4 columns]

In [33]:
sales_train = pd.read_csv(datapath + 'sales.csv')
sales_train

            Date     Revenue        COGS
0     2012-07-04  5123547.94  3982991.19
1     2012-07-05  2751773.45  2150580.23
2     2012-07-06  3054029.42  2517632.84
3     2012-07-07  2667930.94  2108246.62
4     2012-07-08  2360851.90  1808622.79
...          ...         ...         ...
3828  2022-12-27  2100553.66  2184872.24
3829  2022-12-28  3448729.20  3513621.00
3830  2022-12-29  3083944.33  3170787.10
3831  2022-12-30  2884668.76  3022292.15
3832  2022-12-31  2383037.48  2279288.13

[3833 rows x 3 columns]

In [34]:
orders

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,prev_date,order_gap
4023,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search,NaT,NaT
143252,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral,2012-07-25,675 days
238890,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search,2014-05-31,426 days
374571,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search,2015-07-31,632 days
544446,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search,2017-04-23,1037 days
...,...,...,...,...,...,...,...,...,...,...
549990,709267,2020-04-11,157563,59937,delivered,credit_card,mobile,email_campaign,2019-08-30,225 days
557438,718824,2020-05-29,157563,59937,delivered,credit_card,mobile,social_media,2020-04-11,48 days
559725,721751,2020-06-22,157563,59937,delivered,paypal,tablet,organic_search,2020-05-29,24 days
591841,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media,2020-06-22,339 days
637881,822601,2022-08-31,157563,59937,cancelled,cod,desktop,social_media,2021-05-27,461 days

In [35]:
order_items

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2
0,1,2400,7,1138.22,0.0,NaN,NaN
1,2,609,7,10166.25,0.0,NaN,NaN
2,3,396,3,11220.33,0.0,NaN,NaN
3,4,635,5,10639.25,0.0,NaN,NaN
4,6,1935,1,1597.84,0.0,NaN,NaN
...,...,...,...,...,...,...,...
714664,834372,690,8,4473.92,0.0,NaN,NaN
714665,834377,1995,7,5250.79,0.0,NaN,NaN
714666,834387,2331,8,7389.06,0.0,NaN,NaN
714667,834392,1115,5,4767.33,0.0,NaN,NaN
714668,834397,1118,1,4716.75,0.0,NaN,NaN

In [36]:
order_items['revenue'] = order_items['unit_price'] * order_items['quantity'] - order_items['discount_amount']
order_items

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2,revenue
0,1,2400,7,1138.22,0.0,NaN,NaN,7967.54
1,2,609,7,10166.25,0.0,NaN,NaN,71163.75
2,3,396,3,11220.33,0.0,NaN,NaN,33660.99
3,4,635,5,10639.25,0.0,NaN,NaN,53196.25
4,6,1935,1,1597.84,0.0,NaN,NaN,1597.84
...,...,...,...,...,...,...,...,...
714664,834372,690,8,4473.92,0.0,NaN,NaN,35791.36
714665,834377,1995,7,5250.79,0.0,NaN,NaN,36755.53
714666,834387,2331,8,7389.06,0.0,NaN,NaN,59112.48
714667,834392,1115,5,4767.33,0.0,NaN,NaN,23836.65
714668,834397,1118,1,4716.75,0.0,NaN,NaN,4716.75

In [37]:
orders_with_revenue = orders.merge(order_items[['order_id', 'revenue']], on='order_id')
orders_with_revenue

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,prev_date,order_gap,revenue
0,5280,2012-07-25,1,15201,delivered,cod,desktop,paid_search,NaT,NaT,12627.39
1,184922,2014-05-31,1,15201,returned,credit_card,mobile,referral,2012-07-25,675 days,1478.78
2,308113,2015-07-31,1,15201,delivered,cod,mobile,paid_search,2014-05-31,426 days,44708.32
3,483190,2017-04-23,1,15201,delivered,cod,mobile,paid_search,2015-07-31,632 days,37213.40
4,702081,2020-02-24,1,15201,delivered,credit_card,mobile,organic_search,2017-04-23,1037 days,3528.10
...,...,...,...,...,...,...,...,...,...,...,...
714664,718824,2020-05-29,157563,59937,delivered,credit_card,mobile,social_media,2020-04-11,48 days,139689.28
714665,721751,2020-06-22,157563,59937,delivered,paypal,tablet,organic_search,2020-05-29,24 days,12002.81
714666,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media,2020-06-22,339 days,9174.52
714667,763157,2021-05-27,157563,59937,delivered,credit_card,mobile,social_media,2020-06-22,339 days,19143.00
714668,822601,2022-08-31,157563,59937,cancelled,cod,desktop,social_media,2021-05-27,461 days,70123.83

In [38]:
zip_revenue = orders_with_revenue.groupby('zip')['revenue'].sum()
geography_with_revenue = geography.merge(zip_revenue.to_frame(), on='zip')
geography_with_revenue.groupby('region')['revenue'].sum().sort_values(ascending=False)

region
East       7.291151e+09
Central    4.719491e+09
West       3.670227e+09
Name: revenue, dtype: float64

**Answer:** . East

**Question 8:**

In [39]:
cancelled_orders = orders[orders['order_status']=='cancelled']
cancelled_orders['payment_method'].value_counts()

payment_method
credit_card      28452
cod              15468
paypal            7817
apple_pay         5190
bank_transfer     2535
Name: count, dtype: int64

**Answer:** A. credit_card

**Question 9:**

In [40]:
items_with_products = order_items.merge(products[['product_id', 'size']], on='product_id')
num_size = items_with_products['size'].value_counts()
num_size

size
XL    193025
M     176428
L     173174
S     172042
Name: count, dtype: int64

In [41]:
returned = returns.merge(products[['product_id', 'size']], on='product_id')
returned

,return_id,order_id,product_id,return_date,return_reason,return_quantity,refund_amount,size
0,RET-000001,2,609,2012-07-25,late_delivery,6,52458.01,M
1,RET-000002,32,1862,2012-07-16,wrong_size,2,5141.37,L
2,RET-000003,35,2359,2012-07-16,wrong_size,1,5315.95,XL
3,RET-000004,47,1449,2012-07-11,wrong_size,4,6493.75,M
4,RET-000005,47,1450,2012-07-25,wrong_size,1,1740.76,L
...,...,...,...,...,...,...,...,...
39934,RET-051470,832867,653,2022-12-27,wrong_size,3,24741.62,M
39935,RET-051471,832890,792,2022-12-30,late_delivery,1,560.50,S
39936,RET-051481,833005,449,2022-12-31,defective,1,10002.55,M
39937,RET-051494,833234,1085,2022-12-28,wrong_size,1,815.57,M
39938,RET-051504,833351,2254,2022-12-30,late_delivery,3,1643.47,L

In [42]:
return_quantity = returned.groupby('size')['return_quantity'].sum()
return_quantity

size
L     26688
M     26932
S     26797
XL    29169
Name: return_quantity, dtype: int64

In [43]:
num_return_total = return_quantity.to_frame().join(num_size)
num_return_total

      return_quantity   count
size
L               26688  173174
M               26932  176428
S               26797  172042
XL              29169  193025

In [44]:
return_rate = num_return_total['return_quantity'] / num_return_total['count']
return_rate.sort_values(ascending=False)

size
S     0.155758
L     0.154111
M     0.152652
XL    0.151115
dtype: float64

**Answer:** A. S

**Question 10:**

In [45]:
payments = pd.read_csv(datapath + 'payments.csv')
payments

        order_id payment_method  payment_value  installments
0              1    credit_card        7967.54             3
1              2            cod       71163.75             1
2              3    credit_card       33660.99             3
3              4    credit_card       53196.25             3
4              6         paypal        1597.84             1
...          ...            ...            ...           ...
646940    834372    credit_card       35791.36             3
646941    834377    credit_card       36755.53             3
646942    834387    credit_card       59112.48             1
646943    834392         paypal       23836.65             1
646944    834397    credit_card        4716.75             3

[646945 rows x 4 columns]

In [46]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  int64
 1   payment_method  646945 non-null  str
 2   payment_value   646945 non-null  float64
 3   installments    646945 non-null  int64
dtypes: float64(1), int64(2), str(1)
memory usage: 19.7 MB

In [47]:
payments.groupby('installments')['payment_value'].mean().sort_values(ascending=False)

installments
6     24446.654403
3     24399.635486
12    24245.772694
1     24113.274166
2       708.473729
Name: payment_value, dtype: float64

**Answer:** C. 6 kỳ